### ISSUE TITLE
CRS Error

### ISSUE THREAD

**Issue by andrew-vancil** [geomarker-io/appc#53]
Receiving an error when trying to run the first example on the Readme. 
```
> appc::predict_pm25(
    x = s2::as_s2_cell(c("8841b39a7c46e25f", "8841a45555555555")),
    dates = list(as.Date(c("2023-05-18", "2023-11-06")), as.Date(c("2023-06-22", "2023-08-15"))),
    quiet = FALSE
)

loading random forest model...
checking input s2 locations and dates
checking that s2 locations are within the contiguous united states
adding HMS smoke data
progress bar doesn't work in RStudio; follow the file ".progress" instead
adding coordinates
adding elevation
adding AADT using level 14 s2 approximation (~ 260 m sq)
adding NARR
Error: [project] output crs is not valid
In addition: Warning message:
[rast] unknown extent 
```

**Comment by cole-brokamp** [comment]
it looks like an error when you are adding the NARR data.  Can you run that example for that function to be sure? https://geomarker.io/appc/reference/get_narr_data.html

Also check to make sure that you are using a recent version of terra and sf.  It seems like the error message is related to one of those packages given the "output crs" mention.

**Comment by andrew-vancil** [comment]
After manually installing gdal into my current project, I was able to successfully update terra, reinstall appc and run the given example with no issues.
