### ISSUE TITLE
error building vignettes / running examples... related to tigris caching? 

### ISSUE THREAD

**Issue by erikarasnick** [geomarker-io/appc#63]
If I clone the repo and try to build the package locally without changing anything, I keep getting this error, sometimes when building vignettes and sometimes when running tests. In both cases, the error is triggered by `tigris` calls.

```
Cannot open "/private/var/folders/7f/zd0jc6710pj2mk4wzyv_tj5w0000gr/T/RtmpEdlWqx"; The source could be corrupt or not supported. See `st_drivers()` for a list of supported formats.
```

In my .Rprofile I changed `tigris_use_cache` to `FALSE` but I am still getting the error. I think this is more a problem with the way R runs checks on my machine than with the package itself, but just documenting here as I work through it.

**Comment by cole-brokamp** [comment]
I've been wanting to get rid of the dependency on tigris now that we aren't using census tracts for assessing smoke plume data.  We could move it to "Suggests" and check for it to be installed if using the get_census_tract_id() function.  Besides that, it is only used to get the outline of the contiguous united states, and we could 'hard code' that instead.  It would also save us some compute time (#62).

**Comment by cole-brokamp** [comment]
tigris was eliminated in #67
