### ISSUE TITLE
Error pulling estimates with 2024 dates

### ISSUE THREAD

**Issue by cgzundel** [geomarker-io/appc#80]
[appc_test_102924.csv](https://github.com/user-attachments/files/17562462/appc_test_102924.csv)

Hi all, 
I'm running into an error trying to pull newer estimates that include 2024 dates. Here is the R code I am working with: 

d <-
  read_csv(
    "./appc_test_102924.csv",
    col_types = cols(
      SubjectID = col_character(),
      lat = col_double(),
      lon = col_double(),
      start_date = col_date(format = "%m/%d/%y"),
      end_date = col_date(format = "%m/%d/%y")
    )
  )

d <- d |>
  rowwise() |>
  mutate(dates = list(seq(start_date, end_date, by = 1))) |>
  ungroup() |>
  mutate(s2 = s2::as_s2_cell(s2::s2_geog_point(lon, lat)))

d <- d |> dplyr::mutate(pm25 = predict_pm25(s2, dates))

Here is the error it's returning: 
Error in `dplyr::mutate()`:■■■■■■■■■■■■■■■■■■■■■■■■■■■    95% |  ETA:  2s
ℹ In argument: `pm25 = predict_pm25(s2, dates)`.
Caused by error in `purrr::map()`:
ℹ In index: 102.
Caused by error in `purrr::map()`:
ℹ In index: 24.
Caused by error in `st_join.sf()`:
! second argument should be of class sf: maybe revert the first two arguments?
Run `rlang::last_trace()` to see where the error occurred.
✖ adding HMS smoke data [45.7s]          

I've attached an example dataset that has replicated this error.

**Comment by cole-brokamp** [comment]
Hi Clara, I'm getting an error about finding function `read_csv` trying to run the first line of your code.  Are you loading the `readr` package or defining that function somewhere else?

**Comment by cgzundel** [comment]
That's so strange! Those packages were already loaded, but I added to my code: 
library(readr)
library(dplyr)
library(appc) 

And I'm still getting the same error message. 
<img width="711" alt="Screenshot 2024-10-30 at 10 53 51 AM" src="https://github.com/user-attachments/assets/89d81520-6339-4ebd-9269-7627ad7e0f4c">

I have also reinstalled the dplyr package and that didn't change anything. 

Here's the current versions of my packages
<img width="243" alt="Screenshot 2024-10-30 at 10 51 55 AM" src="https://github.com/user-attachments/assets/fc247442-8cfa-4c44-920c-8494017e1669">

**Comment by cgzundel** [comment]
Okay update, I ran it successfully on a windows computer. So it might be a mac issue.... sigh. :(

**Comment by cole-brokamp** [comment]
hmm.  I was successfully testing on a mac.  Are you running in a completely clean session? [reprex](https://reprex.tidyverse.org/) is good for making sure things are running without any influence from the system you are running them on.

**Comment by cgzundel** [comment]
[daft-loon_reprex_preview.pdf](https://github.com/user-attachments/files/17591402/daft-loon_reprex_preview.pdf)
Still getting the error, in a new session, using reprex

**Comment by cole-brokamp** [comment]
Hmm, I'm not getting the same error running your code.  That tells me that it is something related to the environment that the code is running in.  I also removed some code that I thought wasn't necessary.

``` r
library(readr)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(appc)

d <- tibble(
  SubjectID = c("A1", "A2"),
  lat = c(42.3314, 42.2808),
  lon = c(-83.0458, -83.7430),
  start_date = as.Date(c("2024-01-01", "2024-01-02")),
  end_date = as.Date(c("2024-01-05", "2024-01-04"))
)

d <- d |>
  rowwise() |>
  mutate(dates = list(seq(start_date, end_date, by = 1))) |>
  ungroup() |>
  mutate(s2 = s2::as_s2_cell(s2::s2_geog_point(lon, lat)))

d <- d |> dplyr::mutate(pm25 = predict_pm25(s2, dates))
#> ℹ (down)loading random forest model
#> ✔ (down)loading random forest model [11.1s]
#> 
#> ℹ checking that s2 are within the contiguous US
#> ✔ checking that s2 are within the contiguous US [83ms]
#> 
#> ℹ adding coordinates
#> ✔ adding coordinates [8.7s]
#> 
#> ℹ adding elevation
#> ✔ adding elevation [1.4s]
#> 
#> ℹ adding HMS smoke data
#> ✔ adding HMS smoke data [960ms]
#> 
#> ℹ adding NARR
#> ✔ adding NARR [427ms]
#> 
#> ℹ adding gridMET
#> ✔ adding gridMET [399ms]
#> 
#> ℹ adding MERRA
#> ✔ adding MERRA [386ms]
#> 
#> ℹ adding time components
#> ✔ adding time components [30ms]
#> 
```

<sup>Created on 2024-10-31 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
